import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  Coming_Soon,
  Yarndings_12,
  UnifrakturMaguntia,
  Libre_Barcode_39_Extended_Text,
  Jacquard_12_Charted,
  Pixelify_Sans,
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
const metadata: Metadata = {
  title: "PsyCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body className="bg-gray-100">
        <Toaster position="top-center" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
